name: Ejecutar Bot Selenium

on:
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3. Crear un entorno virtual
      - name: Crear entorno virtual
        run: python -m venv .venv

      # 4. Activar el entorno virtual e instalar dependencias
      - name: Instalar dependencias en entorno virtual
        run: |
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Configurar credenciales de Google Drive
      - name: Configure Google Credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > service_account.json

      # 6. Ejecutar el script de Selenium
      - name: Ejecutar script Selenium
        env:
          PORTAL_USER: ${{ secrets.PORTAL_USER }}
          PORTAL_PASSWORD: ${{ secrets.PORTAL_PASSWORD }}
        run: |
          source .venv/bin/activate
          python robot.py

      # 7. Guardar logs como artefacto
      - name: Guardar archivo de log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: robot.log

      # 8. Mensaje de éxito
      - name: Output Success Message
        run: echo "Script ejecutado correctamente en GitHub Actions."
