name: Run Selenium Bot

on:
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instalar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Instalar las dependencias
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 4. Configurar las credenciales de Google Drive (opcional)
      - name: Configure Google Credentials
        if: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > service_account.json

      # 5. Ejecutar el script Selenium
      - name: Run the Selenium script
        env:
          PORTAL_USER: ${{ secrets.PORTAL_USER }}
          PORTAL_PASSWORD: ${{ secrets.PORTAL_PASSWORD }}
        run: |
          python robot.py
