name: Ejecutar Bot Selenium

on:
  workflow_dispatch:
  repository_dispatch:
    types: [execute_workflow]

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3. Crear y activar un entorno virtual
      - name: Crear y configurar entorno virtual
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip

      # 4. Instalar dependencias
      - name: Instalar dependencias
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      # 5. Instalar Google Chrome y ChromeDriver
      - name: Instalar Google Chrome y ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          wget https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.116/linux64/chromedriver-linux64.zip -O chromedriver-linux64.zip
          unzip chromedriver-linux64.zip -d /usr/local/bin/
          sudo mv /usr/local/bin/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          rm -r chromedriver-linux64.zip /usr/local/bin/chromedriver-linux64/

      # 6. Configurar credenciales de Google Drive
      - name: Configurar credenciales de Google Drive
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > service_account.json

      # 7. Ejecutar el script de Selenium
      - name: Ejecutar script Selenium
        env:
          PORTAL_USER: ${{ secrets.PORTAL_USER }}
          PORTAL_PASSWORD: ${{ secrets.PORTAL_PASSWORD }}
        run: |
          source venv/bin/activate
          python robot.py

      # 8. Guardar logs como artefacto
      - name: Guardar archivo de log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: robot.log

      # 9. Mensaje de éxito
      - name: Output Success Message
        run: echo "Script ejecutado correctamente en GitHub Actions."
