name: Ejecutar Bot Selenium

on:
  workflow_dispatch:
  repository_dispatch:
    types: [execute_workflow]

jobs:
  run_bot:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-chrome:latest  # Contenedor preconfigurado con Selenium y Chrome
      options: --user=root 

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3. Instalar dependencias de Python
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Configurar las credenciales de Google Drive
      - name: Configurar credenciales de Google Drive
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > service_account.json

      # 5. Ejecutar el script de Selenium
      - name: Ejecutar script Selenium
        env:
          PORTAL_USER: ${{ secrets.PORTAL_USER }}
          PORTAL_PASSWORD: ${{ secrets.PORTAL_PASSWORD }}
        run: |
          python robot.py

      # 6. Guardar logs como artefacto
      - name: Guardar archivo de log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: robot.log

      # 7. Mensaje de éxito
      - name: Mensaje de éxito
        run: echo "Script ejecutado correctamente en GitHub Actions."
